mcpServers:
  getoutpost-mcp:
    command: "uvicorn"
    args:
      - "mcp_server:app"
      - "--host"
      - "127.0.0.1"
      - "--port"
      - "8000"
    env:
      EMAIL: "ashwinbhskr@gmail.com"
    protocol: "http"
    url: "http://127.0.0.1:8000/mcp"